Feat/anular entrada
udistrital/arka_mid pull request #134
Opened 2021-04-11 03:48 UTC by ludwinggsanchez

closes: udistrital/arka_cliente#592

2021-04-11 04:44 UTC, ludwinggsanchez commented
Para que funcione en producción, se debe agregar la variable de entorno del mid de cuentas contables

2021-04-11 05:12 UTC, AlexFBP requested changes
- Comentar `fmt.Print()`, `fmt.Printf()`, `fmt.Println()` donde la información no sea relevante en funcionamiento correcto de la aplicación
- Control de errores
- En lo posible, aprovechar las utilidades del `utilsHelper` y/o negar la lógica asociada a errores

2021-04-11 06:17 UTC, ludwinggsanchez commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +	urlcrud = "http://" + beego.AppConfig.String("cuentasContablesService") + "cuenta_contable/" + cuentaContableId
- Se agrega el respectivo defer()
- No hace falta agregar validación de tipo de dato dado que este, al ser un id de mongo, es de tipo string

2021-04-11 06:51 UTC, ludwinggsanchez commented on helpers/entradaHelper/entrada.helper.go
> +			urlcrud = "http://" + beego.AppConfig.String("movimientosKronosService") + "movimiento_proceso_externo?query=ProcesoExterno:" + strconv.Itoa(int(movimientoId))
Dado que todos los ```json.Unmarshal()``` se hacen para convertir a un tipo de modelo específico y no a una ```interface{}``` ```map[string]interface{}```, no se pueden utilizar estas funciones. Voy a seguir revisando cómo crear una función a la que le pueda especificar el tipo de variable que retorna.

2021-04-12 03:32 UTC, AlexFBP approved these changes

2021-04-12 03:32 UTC, merged