Feature/movimientos contables entradas
udistrital/arka_mid pull request #174
Opened 2021-09-08 04:26 UTC by juandavidvelezaalvarez

https://github.com/udistrital/arka_mid/issues/115

2021-09-10 07:45 UTC, AlexFBP reviewed
- No olvidar cambiar los `log.Print` o `fmt.Print` por `logs.Debug` o `logs.Info` o el que sea adecuado

2021-09-10 07:45 UTC, AlexFBP commented on helpers/entradaHelper/entrada.helper.go
> +					}
Actualmente:
| `res` | `outputError` entrante | Entra? | `outputError` retornado |
| --- | --- | --- | --- |
| `== nil` | `== nil` | Si | L308-L312 |
| `== nil` | `!= nil` | Si | Original |
| `!= nil` | `== nil` | No | N/A |
| `!= nil` | `!= nil` | Si | Original |

Lo anterior es válido? (Confirmar)

2021-09-10 07:45 UTC, AlexFBP commented on helpers/entradaHelper/entrada.helper.go
> +					return nil, outputError
Revisar:
Si se llega al `return` de la L340 es porque en la L321 `err == nil`. En otras palabras, en ambos casos se está retornando un `nil, outputError`

2021-09-21 14:28 UTC, juandavidvelezaalvarez commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +	var (
Corregido

2021-09-21 14:28 UTC, juandavidvelezaalvarez commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +		outputError = map[string]interface{}{"funcion": "asientoContable - if err := request.GetJson(urlcrud, &resMap);", "status": "500", "err": err}
Corregido

2021-09-21 14:28 UTC, juandavidvelezaalvarez commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +		outputError = map[string]interface{}{"funcion": "asientoContable - if err := request.GetJson(urlcrud, &resMap);", "status": "500", "err": err}
Corregido

2021-09-21 14:28 UTC, juandavidvelezaalvarez commented on helpers/entradaHelper/entrada.helper.go
> +								log.Print("por el put")
Corregido

2021-09-21 14:31 UTC, juandavidvelezaalvarez commented on helpers/entradaHelper/entrada.helper.go
> +					return nil, outputError
Fue un malentendido por la indentación

2021-09-22 02:38 UTC, juandavidvelezaalvarez commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +					outputError = map[string]interface{}{"funcion": "asientoContable - if len(element) == 0 ", "status": "500", "err": err}
Escogí 406 Not Acceptable.  Porque la razón de ese if es que no hay cuenta, si no hay cuenta es un error del usuario que no configuró bien.  Y dentro de los errores http 4xx ese me pareció el más apropiado.

2021-09-25 04:48 UTC, AlexFBP requested changes
- Hay varios cambios sugeridos (se pueden aplicar directamente desde GitHub)
- Hay partes en que hay que revisar/confirmar la lógica
- En algunos lados falta imprimir el error en consola

2021-09-25 04:48 UTC, AlexFBP commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +		outputError = map[string]interface{}{"funcion": "asientoContable - if err := request.GetJson(urlcrud, &resMap);", "status": "502", "err": err}
Falta colocar antes de esta línea el `logs.Error(err)`

2021-09-25 04:48 UTC, AlexFBP commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +		outputError = map[string]interface{}{"funcion": "asientoContable - if jsonString, err1 = json.Marshal(resMap[\"Data\"]);", "status": "500", "err": err1}
Falta colocar antes de esta línea el `logs.Error(err1)`

2021-09-25 04:48 UTC, AlexFBP commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +		outputError = map[string]interface{}{"funcion": "asientoContable - if err1 = json.Unmarshal(jsonString, &parametro);", "status": "500", "err": err1}
Falta colocar antes de esta línea el `logs.Error(err1)`

2021-09-25 04:48 UTC, AlexFBP commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +		outputError = map[string]interface{}{"funcion": "asientoContable - if err1 = request.GetJson(urlcrud, &resMap);", "status": "502", "err": err1}
Falta colocar antes de esta línea el `logs.Error(err1)`

2021-09-25 04:48 UTC, AlexFBP commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +		outputError = map[string]interface{}{"funcion": "asientoContable - if jsonString, err1 = json.Marshal(resMap[\"Data\"]);", "status": "500", "err": err1}
Falta colocar antes de esta línea el `logs.Error(err1)`

2021-09-25 04:48 UTC, AlexFBP commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +		outputError = map[string]interface{}{"funcion": "asientoContable - if err1 = json.Unmarshal(jsonString, &parametro);", "status": "500", "err": err1}
Falta colocar antes de esta línea el `logs.Error(err1)`

2021-09-25 04:48 UTC, AlexFBP commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +		outputError = map[string]interface{}{"funcion": "asientoContable - if jsonString, err1 = json.Marshal(etiquetas);", "status": "500", "err": err1}
Falta colocar antes de esta línea el `logs.Error(err1)`

2021-09-25 04:48 UTC, AlexFBP commented on helpers/cuentasContablesHelper/cuentasContables.helper.go
> +					outputError = map[string]interface{}{"funcion": "asientoContable - if len(element) == 0 ", "status": "500", "err": err}
Falta colocar antes de esta línea el `logs.Error(err)`

2021-09-25 04:48 UTC, AlexFBP commented on helpers/entradaHelper/entrada.helper.go
> +								logs.Debug("por el put")
Usar un único `logs.Debug()` (se le pueden pasar varios parámetros a la vez)

2021-09-25 04:48 UTC, AlexFBP commented on helpers/entradaHelper/entrada.helper.go
> +								return nil, outputError
Revisar y/o confirmar la lógica:
Una vez se retorna en esta línea (142), el código que va de las líneas 143 a 161 no se va a ejecutar.
Si ese es el caso, eliminarlo, o revisar qué pasó acá...

El editor de hecho lo está indicando también:
![image](https://user-images.githubusercontent.com/6588872/134757838-79007d47-1e35-4972-8cc8-49260404a0c3.png)

2021-09-25 04:48 UTC, AlexFBP commented on helpers/entradaHelper/entrada.helper.go
> +									"err":     err,
Revisar y/o confirmar la lógica:
- Bajo este contexto, el `err` que toma es el declarado en la L106, que a su vez fue evaluado como `err == nil`.
- Cuando se ejecuten las líneas 135 en adelante, el `err`or retornado será `nil`
- Adicionalmente, la única razón para que se ejecuten estas líneas (de la 135 en adelante), es porque previamente se haya ejecutado la L116, la cual se observa o parece que es el comportamiento deseado, pero se estaría retornando como error...

Ver el comentario de la L309, que parece ser otro caso similar...

2021-09-25 04:48 UTC, AlexFBP commented on helpers/entradaHelper/entrada.helper.go
> +					//fmt.Println(resA)
Eliminar este comentario (ya se está usando el `logs.Debug()`)

2021-09-25 04:48 UTC, AlexFBP commented on helpers/entradaHelper/entrada.helper.go
> +					logs.Debug(resA)
EN GENERAL
La idea es que los logs ayuden, evitar imprimir solamente las variables, hacerlos más descriptivos. Por ejemplo, no más indicar qué es lo que se está imprimiendo en consola, bastaría:
```suggestion
					logs.Debug("resA:", resA)
```

2021-09-25 04:48 UTC, AlexFBP commented on helpers/entradaHelper/entrada.helper.go
> +								"err":     err,
Revisar / confirmar la lógica:

- Es claro que, para que se ejecute el código de las líneas 307 a 311 es porque `res == nil`.
- Bajo este contexto, `err` está tal cual como fué definida en la L291, donde a su vez fue evaluado como `err == nil`
- Por lo anterior, el `outputError["err"]` sería `nil`

En vez del `err`, que actualmente sería `nil`; se podría usar, entre otras opciones, alguna de los siguientes:
- Un mero string, indicando exactamente cuál fue el error
- Usar `fmt.Errorf()` para generar un error formateado (esto cubre también la opción anterior)

Nótese que este caso es similar al comentado/observado en la L139

Alternativa/Adicionalmente, y dado que también falta imprimir el `err`, las opciones anteriores se pueden combinar, usar; para declarar la variable `err` justo antes del `outputError`, podría ser algo así
```diff
 if outputError == nil {
+  err := fmt.Errorf("no se cumple tal condición")
+  logs.Error(err)
   outputError = map[string]interface{}{
```

2022-03-31 15:09 UTC, AlexFBP commented
Aparentemente esto ya está implementado, se cerrará mientras tanto

2022-03-31 15:09 UTC, closed without merging