Feature/traslados
udistrital/arka_mid pull request #194
Opened 2021-11-30 02:32 UTC by ludwinggsanchez

Relacionado con udistrital/arka_cliente#844

2021-11-30 18:13 UTC, AlexFBP requested changes
Ta buena la parte de los controladores, y bueno, en general bien.

2021-11-30 18:13 UTC, AlexFBP commented on helpers/actaRecibidoCrud/actaRecibidoCrud.go
> +}
(ver lo comentado en `helpers/actaRecibido/actaRecibido.helper.go`)
Se recomienda que este archivo haga parte del mismo paquete `helpers/actaRecibido`, se podría guardar allá como `service.go`, o bueno, igual, `actaRecibidoCrud.go`, realmente no importa, lo que importa es que tenga las peticiones que se estén haciendo a ese crud

2021-11-30 18:13 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +			outputError = map[string]interface{}{"funcion": "/GetDetalleElemento", "err": err, "status": "502"}
```suggestion
			outputError = map[string]interface{}{"funcion": "/GetDetalleElemento - Unhandled Error!", "err": err, "status": "500"}
```
Se recomienda combinar esto con el uso de utils_oas/errorctrl para no repetir tanto código

2021-11-30 18:13 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	}
Adicional a lo comentado en ...
- `helpers/actaRecibidoCrud/actaRecibidoCrud.go`
- L991 a 997 de `helpers/actaRecibido/actaRecibido.helper.go`
Mover-a/reutilizar un helper de `helpers/movimientosArkaHelper`

2021-11-30 18:13 UTC, AlexFBP commented on helpers/salidaHelper/salida.helepr.go
> +	urlcrud := "http://" + beego.AppConfig.String("movimientosArkaService") + "movimiento?limit=-1&sortby=Id&order=desc"
Si bien se sale del alcance de este PR, revisar si es posible reescribir un poco esta parte para que aproveche un helper de `helpers/movimientosArkaHelper`

2021-12-04 11:34 UTC, ludwinggsanchez commented on helpers/actaRecibido/actaRecibido.helper.go
> +	if actaId > 0 || len(ids) > 0 { // (1) error parametro
Exacto

2021-12-05 05:54 UTC, AlexFBP requested changes
En general bien. De los comentarios dejados, la mayoría se dividen en los siguientes:
- Si en una de las ramas de un `if` hay un `return` o un `panic` "obligado", se puede omitir el `else` para reducir uno o más niveles de indentación. Tratar de aplicarlo y en donde no se pueda o sea inviable, replicarlo en el mismo comentario. En varios de los casos es posible que toque crear una o mas variables previamente para aplicar esto....
- En código nuevo, tratar de aprovechar las `utils_oas`. Entre otras, `errorctrl`y `formatData.FillStruct`

2021-12-05 05:54 UTC, AlexFBP commented on controllers/bajas.go
> +	}
- En el controlador validar únicamente que los parámetros sean del tipo adecuado, hay cierta interdependencia entre los parámetros? Mover la interdependencia, la lógica, al helper
- `c.GetXxx` tiene una segunda forma en que acepta un valor por defecto como segundo parámetro

Con lo anterior...
```go
var revComite bool
if v, err := c.GetBool("revComite", false); err != nil {
	logs.Error(err)
	panic(map[string]interface{}{
		"funcion": "GetAll - GetBool(\"revComite\")",
		"err":     err,
		"status":  "400",
	})
}
var revAlmacen bool
if v, err := c.GetBool("revAlmacen"); err != nil {
	logs.Error(err)
	panic(map[string]interface{}{
		"funcion": "GetAll - GetBool(\"revAlmacen\")",
		"err":     err,
		"status":  "400",
	})
}
```
Lo anterior se puede reducir aún más si se aprovecha `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/actaRecibido/actaRecibidoCrud.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/actaRecibido/actaRecibidoCrud.go
> +		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +func GetAllElementosMovimiento(query string) (elementos []*models.ElementosMovimiento, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "GetAllElementosMovimiento hace tal cosa"
```suggestion
// GetAllElementosMovimiento ...
func GetAllElementosMovimiento(query string) (elementos []*models.ElementosMovimiento, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +func GetAllSoporteMovimiento(query string) (soportes []*models.SoporteMovimiento, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "GetAllSoporteMovimiento hace tal cosa"
```suggestion
// GetAllSoporteMovimiento ...
func GetAllSoporteMovimiento(query string) (soportes []*models.SoporteMovimiento, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +func GetAllMovimiento(query string) (movimientos []*models.Movimiento, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "GetAllMovimiento hace tal cosa"
```suggestion
// GetAllMovimiento ...
func GetAllMovimiento(query string) (movimientos []*models.Movimiento, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +func PostSoporteMovimiento(soporte *models.SoporteMovimiento) (soporteR *models.SoporteMovimiento, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "PostSoporteMovimiento hace tal cosa"
```suggestion
// PostSoporteMovimiento ...
func PostSoporteMovimiento(soporte *models.SoporteMovimiento) (soporteR *models.SoporteMovimiento, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +func PutSoporteMovimiento(soporte *models.SoporteMovimiento, soporteId int) (soporteR *models.SoporteMovimiento, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "PutSoporteMovimiento hace tal cosa"
```suggestion
// PutSoporteMovimiento ...
func PutSoporteMovimiento(soporte *models.SoporteMovimiento, soporteId int) (soporteR *models.SoporteMovimiento, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/salidaHelper/salida.helepr.go
> +	} else {
Dado que en el `if` hay un `return`, se puede sacar el contenido del `else`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/tercerosHelper/tercero.helper.go
> +func GetTerceroById(id int) (tercero *models.Tercero, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "GetTerceroById hace tal cosa"
```suggestion
// GetTerceroById ...
func GetTerceroById(id int) (tercero *models.Tercero, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/tercerosMidHelper/propiedad.go
> +func GetDocumentoTercero(id int) (documento []*models.DatosIdentificacion, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "GetDocumentoTercero hace tal cosa"
```suggestion
// GetDocumentoTercero ...
func GetDocumentoTercero(id int) (documento []*models.DatosIdentificacion, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/tercerosMidHelper/propiedad.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/tercerosMidHelper/propiedad.go
> +		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/tercerosMidHelper/tercerosMidHelper.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/tercerosMidHelper/tercerosMidHelper.go
> +	} else {
En ambos casos, se puede omitir el `else` dado que hay un retorno. Sin embargo, se entiende que habría que reutilizar y/o crear las variables  xyz

2021-12-05 05:54 UTC, AlexFBP commented on helpers/tercerosHelper/tercero.helper.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/tercerosHelper/tercero.helper.go
> +		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +		panic(err.Error())
Helper, cambiar el panic por un retorno de un error formateado
Aprovechar el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
>  				}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
>  		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
>  		panic(err.Error())
Helper, cambiar el panic por un retorno de un error formateado
Aprovechar el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +				panic(err.Error())
Helper, cambiar el panic por un retorno de un error formateado
Aprovechar el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/actaRecibido/actaRecibidoCrud.go
> +func GetAllElemento(query string) (elementos []*models.Elemento, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "GetAllElemento hace tal cosa"
```suggestion
// GetAllElemento ...
func GetAllElemento(query string) (elementos []*models.Elemento, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +func GetAllSolicitudes(revComite bool, revAlmacen bool) (listBajas []*models.DetalleBaja, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "GetAllSolicitudes hace tal cosa"
```suggestion
// GetAllSolicitudes ...
func GetAllSolicitudes(revComite bool, revAlmacen bool) (listBajas []*models.DetalleBaja, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +func TraerDetalle(id int) (Baja *models.TrBaja, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "TraerDetalle hace tal cosa"
```suggestion
// TraerDetalle ...
func TraerDetalle(id int) (Baja *models.TrBaja, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
>  func GetDetalleElemento(id int) (Elemento *models.DetalleElementoBaja, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "GetDetalleElemento hace tal cosa"
```suggestion
// GetDetalleElemento ...
func GetDetalleElemento(id int) (Elemento *models.DetalleElementoBaja, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +func GetDetalleElementos(ids []int) (Elementos []*models.DetalleElementoBaja, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "GetDetalleElementos hace tal cosa"
```suggestion
// GetDetalleElementos ...
func GetDetalleElementos(ids []int) (Elementos []*models.DetalleElementoBaja, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +			outputError = map[string]interface{}{"funcion": "/GetDetalleElemento - Unhandled Error!", "err": err, "status": "500"}
Esto (no solo esta línea sino toda la `defer func`) se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on controllers/bajas.go
> +			})
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on controllers/bajas.go
> +		})
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on controllers/bajas.go
> +		})
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on controllers/bajas.go
> +			})
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on controllers/bajas.go
> +		})
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/actaRecibido/actaRecibidoCrud.go
> +func GetElementoById(id int) (elemento *models.Elemento, outputError map[string]interface{}) {
Falta documentar, cambiar `...` en el _suggested change_, digamos "GetElementoById hace tal cosa"
```suggestion
// GetElementoById ...
func GetElementoById(id int) (elemento *models.Elemento, outputError map[string]interface{}) {
```

2021-12-05 05:54 UTC, AlexFBP commented on helpers/actaRecibido/actaRecibidoCrud.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/actaRecibido/actaRecibidoCrud.go
> +		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +			outputError = map[string]interface{}{"funcion": "/GetAllElementosMovimiento", "err": err, "status": "500"}
Esto (incluyendo la `defer func`)  se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +			outputError = map[string]interface{}{"funcion": "/GetAllSoporteMovimiento", "err": err, "status": "500"}
Esto (incluyendo la `defer func`) se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
>  				}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	}()
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-05 05:54 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		}
Esto se puede reducir/reescribir un poco si se aprovecha el `utils_oas/errorctrl`

2021-12-06 13:44 UTC, AlexFBP requested changes
En general bien. Los comentarios quedaron todos como _suggested change_

2021-12-06 13:44 UTC, AlexFBP commented on controllers/bajas.go
> +		panic(errorctrl.Error("Put", "c.GetInt(\":id\")", "400"))
```suggestion
		panic(errorctrl.Error("Put - c.GetInt(\":id\")", err, "400"))
```

2021-12-06 13:44 UTC, AlexFBP commented on controllers/bajas.go
> +		panic(errorctrl.Error("Put", "json.Unmarshal(c.Ctx.Input.RequestBody, &v)", "400"))
Faltaba negar la condición del `if`... ?
```suggestion
	if err := json.Unmarshal(c.Ctx.Input.RequestBody, &v); err != nil {
		panic(errorctrl.Error("Put - json.Unmarshal(c.Ctx.Input.RequestBody, &v)", err, "400"))
```

2021-12-06 13:44 UTC, AlexFBP commented on controllers/bajas.go
> +		panic(errorctrl.Error("GetAll", "c.GetBool(\"revComite\", false)", "400"))
```suggestion
		panic(errorctrl.Error("GetAll - c.GetBool(\"revComite\", false)", err, "400"))
```

2021-12-06 13:44 UTC, AlexFBP commented on controllers/bajas.go
> +		panic(errorctrl.Error("GetAll", "c.GetBool(\"revAlmacen\", false)", "400"))
```suggestion
		panic(errorctrl.Error("GetAll - c.GetBool(\"revAlmacen\", false)", err, "400"))
```

2021-12-06 13:44 UTC, AlexFBP commented on controllers/bajas.go
> +		panic(errorctrl.Error("PutRevision", "json.Unmarshal(c.Ctx.Input.RequestBody, &trBaja)", "400"))
```suggestion
		panic(errorctrl.Error("PutRevision - json.Unmarshal(c.Ctx.Input.RequestBody, &trBaja)", err, "400"))
```

2021-12-06 13:44 UTC, AlexFBP commented on controllers/bajas.go
> +		panic(errorctrl.Error("PutRevision", "bajasHelper.AprobarBajas(trBaja)", "404"))
```suggestion
		panic(errorctrl.Error("PutRevision - bajasHelper.AprobarBajas(trBaja)", err, "404"))
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/actaRecibido/actaRecibidoCrud.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/actaRecibido/actaRecibidoCrud.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/actaRecibido/actaRecibidoCrud.go
> +		return nil, errorctrl.Error(funcion, err, "502")
```suggestion
		eval := " - request.GetJson(urlcrud, &elemento)"
		return nil, errorctrl.Error(funcion + eval, err, "502")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/actaRecibido/actaRecibidoCrud.go
> +		return nil, errorctrl.Error(funcion, err, "502")
```suggestion
		eval := " - request.GetJson(urlcrud, &elementos)"
		return nil, errorctrl.Error(funcion + eval, err, "502")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +		return nil, errorctrl.Error(funcion, err, "500")
(En general) Para preveer posibles logs raros que se podrían registrar como sucesivas concatenaciones de errores, en caso que hayan errores que no sean críticos y se puedan dejar pasar, `funcion` se estaría reescribiendo si se trabaja sobre ella misma...
```suggestion
		eval := " - json.Unmarshal([]byte(baja.Movimiento.Detalle), &detalleJSON)"
		return nil, errorctrl.Error(funcion + eval, err, "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +		return nil, errorctrl.Error(funcion, err, "500")
```suggestion
		eval := " - json.Marshal(detalleJSON)"
		return nil, errorctrl.Error(funcion + eval, err, "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +			return nil, errorctrl.Error(funcion, err, "500")
```suggestion
			eval := " - json.Unmarshal([]byte(mov.Detalle), &detalle)"
			return nil, errorctrl.Error(funcion + eval, err, "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +					return nil, errorctrl.Error(funcion, err, "500")
```suggestion
					eval := " - formatdata.FillStruct(ctaCr_, &ctaCr)"
					return nil, errorctrl.Error(funcion + eval, err, "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +					return nil, errorctrl.Error(funcion, err, "500")
```suggestion
					eval := " - formatdata.FillStruct(ctaDb_, &ctaDb)"
					return nil, errorctrl.Error(funcion + eval, err, "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +				return nil, errorctrl.Error(funcion, err, "500")
```suggestion
				eval := " - json.Unmarshal([]byte(solicitud.Detalle), &detalle)"
				return nil, errorctrl.Error(funcion + eval, err, "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +		return nil, errorctrl.Error(funcion, err, "500")
```suggestion
		eval := " - request.SendJson(urlcrud, \"PUT\", &ids, &revision)"
		return nil, errorctrl.Error(funcion + eval, err, "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +		return nil, errorctrl.Error(funcion, err, "500")
```suggestion
		eval := " - json.Unmarshal([]byte(elementoMovimiento.MovimientoId.Detalle), &detalleJSON)"
		return nil, errorctrl.Error(funcion + eval, err, "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/bajasHelper/bajasHelper.helper.go
> +				return nil, errorctrl.Error(funcion, err, "500")
```suggestion
				eval := " - json.Unmarshal([]byte(elementosMovimiento[i].MovimientoId.Detalle), &detalleJSON)"
				return nil, errorctrl.Error(funcion + eval, err, "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/catalogoElementosHelper/catalogoElementosCrud.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on controllers/bajas.go
> +		panic(errorctrl.Error("Post", "json.Unmarshal(c.Ctx.Input.RequestBody, &v)", "400"))
```suggestion
		panic(errorctrl.Error("Post - json.Unmarshal(c.Ctx.Input.RequestBody, &v)", err, "400"))
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		return nil, errorctrl.Error(funcion, err, "502")
```suggestion
		eval := " - request.GetJson(urlcrud, &elementos)"
		return nil, errorctrl.Error(funcion + eval, err, "502")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		return nil, errorctrl.Error(funcion, err, "502")
```suggestion
		eval := " - request.GetJson(urlcrud, &soportes)"
		return nil, errorctrl.Error(funcion + eval, err, "502")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		return nil, errorctrl.Error(funcion, err, "502")
```suggestion
		eval := " - request.GetJson(urlcrud, &movimientos)"
		return nil, errorctrl.Error(funcion + eval, err, "502")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		return nil, errorctrl.Error(funcion, err, "502")
```suggestion
		eval := " - request.GetJson(urlcrud, &movimiento)"
		return nil, errorctrl.Error(funcion + eval, err, "502")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		return nil, errorctrl.Error(funcion, err, "502")
```suggestion
		eval := " - request.SendJson(urlcrud, \"POST\", &res, &movimiento)"
		return nil, errorctrl.Error(funcion + eval, err, "502")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		return nil, errorctrl.Error(funcion, err, "502")
```suggestion
		eval := " - request.SendJson(urlcrud, \"POST\", &soporteR, &soporte)"
		return nil, errorctrl.Error(funcion + eval, err, "502")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		return nil, errorctrl.Error(funcion, err, "502")
```suggestion
		eval := " - request.SendJson(urlcrud, \"PUT\", &trResultado, &trSalida)"
		return nil, errorctrl.Error(funcion + eval, err, "502")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +		return nil, errorctrl.Error(funcion, err, "502")
```suggestion
		eval := " - request.SendJson(urlcrud, \"PUT\", &movimientoRes, &movimiento)"
		return nil, errorctrl.Error(funcion + eval, err, "502")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/movimientosArkaHelper/movimientosArkaHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/tercerosHelper/tercero.helper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/tercerosMidHelper/propiedad.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 13:44 UTC, AlexFBP commented on helpers/tercerosMidHelper/tercerosMidHelper.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion + " - Unhandled Error!", "500")
```

2021-12-06 20:53 UTC, AlexFBP approved these changes

2021-12-06 20:53 UTC, merged