Feature/ajuste contable
udistrital/arka_mid pull request #220
Opened 2022-01-15 09:41 UTC by ludwinggsanchez

Relacionado con udistrital/arka_cliente#574

2022-01-15 17:30 UTC, AlexFBP requested changes
En general bien. Algunos comentarios menores

2022-01-15 17:30 UTC, AlexFBP commented on helpers/ajustesHelper/ajustes.helper.go
> +}
Mover a un archivo aparte en `models`

2022-01-15 17:30 UTC, AlexFBP commented on helpers/ajustesHelper/ajustes.helper.go
> +	}
Revisar: Si es posible que estos parámetros se vuelvan a usar en otro lugar, se recomienda crear un par de helpers adicionales...

2022-01-17 05:51 UTC, ludwinggsanchez commented on helpers/ajustesHelper/ajustes.helper.go
> +	}
Se crea helper adicional y se implementa

2022-01-17 06:02 UTC, AlexFBP approved these changes

2022-01-17 06:02 UTC, merged