Feature/hallazgos bodega
udistrital/arka_mid pull request #242
Opened 2022-04-29 22:32 UTC by ludwinggsanchez

Relacionado con udistrital/arka_cliente#854

2022-04-30 06:14 UTC, AlexFBP requested changes
En general, bien

2022-04-30 06:14 UTC, AlexFBP commented on helpers/salidaHelper/PutTrSalidas.go
>  						outputError = map[string]interface{}{
Dado que `consecutivo` ahora existe fuera del `if`, se puede prescindir del `else` moviendo las L130-146 afuera/después del `if(/else)`

2022-04-30 06:14 UTC, AlexFBP commented on helpers/salidaHelper/salida.go
>  				outputError = map[string]interface{}{
Dado que `consecutivo` ahora existe fuera del `if`, se puede prescindir de su `else` moviendo las L142-154 afuera/después del `if(/else)` respectivo

2022-04-30 06:14 UTC, AlexFBP commented on helpers/trasladosHelper/trasladosHelper.go
>  	}
Dado que `consecutivo` está declarado fuera del `if` y este retorna, se puede prescindir del `else` moviendo las L172-173 afuera/después del `if(/else)`

2022-04-30 06:14 UTC, AlexFBP commented on helpers/trasladosHelper/trasladosHelper.go
> +	if err := crudMovimientosArka.PostMovimiento(data); err != nil {
Revisar: Quizás falte esto ... ?
```suggestion
	if err := crudMovimientosArka.PostMovimiento(&data); err != nil {
```

2022-04-30 06:14 UTC, AlexFBP commented on helpers/utilsHelper/Marshal.go
> +func Marshal(in interface{}, out *string) (outputError map[string]interface{}) {
Documentar...
```suggestion
// Marshal hace tal cosa...
func Marshal(in interface{}, out *string) (outputError map[string]interface{}) {
```

PD: Si es conveniente, mover a [`formatdata`](https://github.com/udistrital/utils_oas/tree/master/formatdata)

2022-04-30 06:14 UTC, AlexFBP commented on helpers/utilsHelper/Unmarshal.go
> +func Unmarshal(in string, out interface{}) (outputError map[string]interface{}) {
Documentar...
```suggestion
// Unmarshal hace tal cosa...
func Unmarshal(in string, out interface{}) (outputError map[string]interface{}) {
```

PD: Si es conveniente, mover a [`formatdata`](https://github.com/udistrital/utils_oas/tree/master/formatdata)

2022-05-02 17:10 UTC, AlexFBP requested changes
En general, bien
Un par de ajustes y quedaría

2022-05-03 01:12 UTC, ludwinggsanchez commented on helpers/bodegaConsumoHelper/GetAllSolicitudes.go
> +	query := "limit=-1&sortby=FechaCreacion&order=desc&query=Activo:true,FormatoTipoMovimientoId__CodigoAbreviacion:SOL_BOD"
Falla.

2022-05-03 02:04 UTC, AlexFBP approved these changes

2022-05-03 02:05 UTC, merged